[package]
name = "basic"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
cdrs-tokio = "4.0.0"
tokio = { version = "1.1.0", features = ["full"] }
getopts = "0.2.12"
anyhow = "1.0.40"

[profile.release]
lto = true